apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/lukastraenklehse/pvs-backend:main
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://database:5432/shoppingdb
            - name: SPRING_DATASOURCE_USERNAME
              value: username
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
